/**
 * Copyright (C) 2020 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package android.content.pm.parsing.component;


/**
 *
 *
 * @unknown 
 */
// @formatter:on
// End of generated code
@com.android.internal.util.DataClass(genGetters = true, genSetters = false, genParcelable = true, genAidl = false, genBuilder = false)
public class ParsedProcess implements android.os.Parcelable {
    @android.annotation.NonNull
    protected java.lang.String name;

    @android.annotation.NonNull
    @com.android.internal.util.DataClass.ParcelWith(Parcelling.BuiltIn.ForInternedStringSet.class)
    protected java.util.Set<java.lang.String> deniedPermissions = java.util.Collections.emptySet();

    protected int gwpAsanMode = -1;

    public ParsedProcess() {
    }

    public ParsedProcess(@android.annotation.NonNull
    android.content.pm.parsing.component.ParsedProcess other) {
        name = other.name;
        deniedPermissions = new android.util.ArraySet(other.deniedPermissions);
    }

    public void addStateFrom(@android.annotation.NonNull
    android.content.pm.parsing.component.ParsedProcess other) {
        deniedPermissions = com.android.internal.util.CollectionUtils.addAll(deniedPermissions, other.deniedPermissions);
    }

    // Code below generated by codegen v1.0.15.
    // 
    // DO NOT MODIFY!
    // CHECKSTYLE:OFF Generated code
    // 
    // To regenerate run:
    // $ codegen $ANDROID_BUILD_TOP/frameworks/base/core/java/android/content/pm/parsing/component/ParsedProcess.java
    // 
    // To exclude the generated code from IntelliJ auto-formatting enable (one-time):
    // Settings > Editor > Code Style > Formatter Control
    // @formatter:off
    @com.android.internal.util.DataClass.Generated.Member
    public ParsedProcess(@android.annotation.NonNull
    java.lang.String name, @android.annotation.NonNull
    java.util.Set<java.lang.String> deniedPermissions, int gwpAsanMode) {
        this.name = name;
        com.android.internal.util.AnnotationValidations.validate(android.annotation.NonNull.class, null, name);
        this.deniedPermissions = deniedPermissions;
        com.android.internal.util.AnnotationValidations.validate(android.annotation.NonNull.class, null, deniedPermissions);
        this.gwpAsanMode = gwpAsanMode;
        // onConstructed(); // You can define this method to get a callback
    }

    @com.android.internal.util.DataClass.Generated.Member
    @android.annotation.NonNull
    public java.lang.String getName() {
        return name;
    }

    @com.android.internal.util.DataClass.Generated.Member
    @android.annotation.NonNull
    public java.util.Set<java.lang.String> getDeniedPermissions() {
        return deniedPermissions;
    }

    @com.android.internal.util.DataClass.Generated.Member
    public int getGwpAsanMode() {
        return gwpAsanMode;
    }

    @com.android.internal.util.DataClass.Generated.Member
    static com.android.internal.util.Parcelling<java.util.Set<java.lang.String>> sParcellingForDeniedPermissions = Parcelling.Cache.get(Parcelling.BuiltIn.ForInternedStringSet.class);

    static {
        if (android.content.pm.parsing.component.ParsedProcess.sParcellingForDeniedPermissions == null) {
            android.content.pm.parsing.component.ParsedProcess.sParcellingForDeniedPermissions = Parcelling.Cache.put(new com.android.internal.util.Parcelling.BuiltIn.ForInternedStringSet());
        }
    }

    @java.lang.Override
    @com.android.internal.util.DataClass.Generated.Member
    public void writeToParcel(@android.annotation.NonNull
    android.os.Parcel dest, int flags) {
        // You can override field parcelling by defining methods like:
        // void parcelFieldName(Parcel dest, int flags) { ... }
        dest.writeString(name);
        android.content.pm.parsing.component.ParsedProcess.sParcellingForDeniedPermissions.parcel(deniedPermissions, dest, flags);
        dest.writeInt(gwpAsanMode);
    }

    @java.lang.Override
    @com.android.internal.util.DataClass.Generated.Member
    public int describeContents() {
        return 0;
    }

    /**
     *
     *
     * @unknown 
     */
    @java.lang.SuppressWarnings({ "unchecked", "RedundantCast" })
    @com.android.internal.util.DataClass.Generated.Member
    protected ParsedProcess(@android.annotation.NonNull
    android.os.Parcel in) {
        // You can override field unparcelling by defining methods like:
        // static FieldType unparcelFieldName(Parcel in) { ... }
        java.lang.String _name = in.readString();
        java.util.Set<java.lang.String> _deniedPermissions = android.content.pm.parsing.component.ParsedProcess.sParcellingForDeniedPermissions.unparcel(in);
        int _gwpAsanMode = in.readInt();
        this.name = _name;
        com.android.internal.util.AnnotationValidations.validate(android.annotation.NonNull.class, null, name);
        this.deniedPermissions = _deniedPermissions;
        com.android.internal.util.AnnotationValidations.validate(android.annotation.NonNull.class, null, deniedPermissions);
        this.gwpAsanMode = _gwpAsanMode;
        // onConstructed(); // You can define this method to get a callback
    }

    @com.android.internal.util.DataClass.Generated.Member
    @android.annotation.NonNull
    public static final android.os.Parcelable.Creator<android.content.pm.parsing.component.ParsedProcess> CREATOR = new android.os.Parcelable.Creator<android.content.pm.parsing.component.ParsedProcess>() {
        @java.lang.Override
        public android.content.pm.parsing.component.ParsedProcess[] newArray(int size) {
            return new android.content.pm.parsing.component.ParsedProcess[size];
        }

        @java.lang.Override
        public android.content.pm.parsing.component.ParsedProcess createFromParcel(@android.annotation.NonNull
        android.os.Parcel in) {
            return new android.content.pm.parsing.component.ParsedProcess(in);
        }
    };

    @DataClass.Generated(time = 1584557524776L, codegenVersion = "1.0.15", sourceFile = "frameworks/base/core/java/android/content/pm/parsing/component/ParsedProcess.java", inputSignatures = "protected @android.annotation.NonNull java.lang.String name\nprotected @android.annotation.NonNull @com.android.internal.util.DataClass.ParcelWith(com.android.internal.util.Parcelling.BuiltIn.ForInternedStringSet.class) java.util.Set<java.lang.String> deniedPermissions\nprotected  int gwpAsanMode\npublic  void addStateFrom(android.content.pm.parsing.component.ParsedProcess)\nclass ParsedProcess extends java.lang.Object implements [android.os.Parcelable]\n@com.android.internal.util.DataClass(genGetters=true, genSetters=false, genParcelable=true, genAidl=false, genBuilder=false)")
    @java.lang.Deprecated
    private void __metadata() {
    }
}

