/**
 * Copyright (C) 2019 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package android.content.om;


/**
 * Immutable info on an overlayable defined inside a target package.
 *
 * @unknown 
 */
@com.android.internal.util.DataClass(genSetters = false, genEqualsHashCode = true, genHiddenConstructor = true)
public final class OverlayableInfo {
    /**
     * The "name" attribute of the overlayable tag. Used to identify the set of resources overlaid.
     */
    @android.annotation.NonNull
    public final java.lang.String name;

    /**
     * The "actor" attribute of the overlayable tag. Used to signal which apps are allowed to
     * modify overlay state for this overlayable.
     */
    @android.annotation.Nullable
    public final java.lang.String actor;

    // CHECKSTYLE:OFF Generated code
    // 
    // Code below generated by codegen v1.0.3.
    // 
    // DO NOT MODIFY!
    // CHECKSTYLE:OFF Generated code
    // 
    // To regenerate run:
    // $ codegen $ANDROID_BUILD_TOP/frameworks/base/core/java/android/content/om/OverlayableInfo.java
    /**
     * Creates a new OverlayableInfo.
     *
     * @param name
     * 		The "name" attribute of the overlayable tag. Used to identify the set of resources overlaid.
     * @param actor
     * 		The "actor" attribute of the overlayable tag. Used to signal which apps are allowed to
     * 		modify overlay state for this overlayable.
     * @unknown 
     */
    @com.android.internal.util.DataClass.Generated.Member
    public OverlayableInfo(@android.annotation.NonNull
    java.lang.String name, @android.annotation.Nullable
    java.lang.String actor) {
        this.name = name;
        com.android.internal.util.AnnotationValidations.validate(android.annotation.NonNull.class, null, name);
        this.actor = actor;
        // onConstructed(); // You can define this method to get a callback
    }

    @java.lang.Override
    @com.android.internal.util.DataClass.Generated.Member
    public boolean equals(java.lang.Object o) {
        // You can override field equality logic by defining either of the methods like:
        // boolean fieldNameEquals(OverlayableInfo other) { ... }
        // boolean fieldNameEquals(FieldType otherValue) { ... }
        if (this == o)
            return true;

        if ((o == null) || (getClass() != o.getClass()))
            return false;

        @java.lang.SuppressWarnings("unchecked")
        android.content.om.OverlayableInfo that = ((android.content.om.OverlayableInfo) (o));
        // noinspection PointlessBooleanExpression
        return (true && java.util.Objects.equals(name, that.name)) && java.util.Objects.equals(actor, that.actor);
    }

    @java.lang.Override
    @com.android.internal.util.DataClass.Generated.Member
    public int hashCode() {
        // You can override field hashCode logic by defining methods like:
        // int fieldNameHashCode() { ... }
        int _hash = 1;
        _hash = (31 * _hash) + java.util.Objects.hashCode(name);
        _hash = (31 * _hash) + java.util.Objects.hashCode(actor);
        return _hash;
    }

    @DataClass.Generated(time = 1570059850579L, codegenVersion = "1.0.3", sourceFile = "frameworks/base/core/java/android/content/om/OverlayableInfo.java", inputSignatures = "public final @android.annotation.NonNull java.lang.String name\npublic final @android.annotation.Nullable java.lang.String actor\nclass OverlayableInfo extends java.lang.Object implements []\n@com.android.internal.util.DataClass(genSetters=false, genEqualsHashCode=true, genHiddenConstructor=true)")
    @java.lang.Deprecated
    private void __metadata() {
    }
}

